### ISSUE TITLE
Self defined unit in SlaveDescription.dcpx

### ISSUE THREAD

**Issue by dev-gb** [modelica/DCPLib#11]
I`ve created a self-defined unit in a DCPSlave and wrote the description to a file.
```C++
Unit_t UnitMS = make_Unit("m/s");
UnitMS.BaseUnit= make_BaseUnit_ptr();
UnitMS.BaseUnit->m = 1;
UnitMS.BaseUnit->s = -1;
slaveDescription.UnitDefinitions.push_back(UnitMS);
  ```
seconds is defined as unsigned integer. 
According to the reverenced FMI Model description units in the denominator are indicated with -1

```XML
FMI 2.0 page 37
<Unit name="rad/s">
    <BaseUnit s="-1" rad="1"/>
</Unit>
```

s should be -1 in the SlaveDescription.dcpx. 
Could someone check that?
```XML
dcpSlaveDescription.dcpx
	<UnitDefinitions>
		<Unit name="m/s" >
			<BaseUnit m="1" s="4294967295" />
		</Unit>
	</UnitDefinitions>
```

**Comment by ChKater** [comment]
There is the wrong data type in the implementation. Inside BaseUnit m, s, ... are uint32 but need to be int32. I will fix this in the next days.

**Comment by ChKater** [comment]
This should be fixed now.
