### ISSUE TITLE
DCPManagerSlave crashes when using Binary Data Type

### ISSUE THREAD

**Issue by dev-gb** [modelica/DCPLib#14]
The Error occurred on using `make_CommonCausality_Binary_ptr()` in `getSlaveDescription()` in the SlaveExample Design 

https://github.com/modelica/DCPLib/blob/8e0085b9d2ecc0a56e140ce6b61b83ff1ee6985e/include/core/dcp/logic/AbstractDcpManagerSlave.hpp#L853-L867

seems like a `break;` is missing in line 860

**Comment by clemensschiffer** [comment]
You are right! 
tested: works.
