### ISSUE TITLE
DcpManagerSlave starts to run in state ALIVE

### ISSUE THREAD

**Issue by dev-gb** [modelica/DCPLib#15]
Tested my DcpSlave with the DcpTestGenerator and noticed that the DcpManagerSlave starts to run a few minutes after the DcpTestGenerator finished successfully.  

The dcp slave, however, indicates to be in the state ALIVE and should not call the `doStep()` function. 
I've debugged the program and noticed some sleeping threads. 
` void startRealtime(int64_t startTime)` is sleeping until `std::this_thread::sleep_until(nextCommunication);`
Same with     `realtimeStepFinished()`
The slave has defined SRT and NRT as operating modes.

This occurred due to a system time mismatch of slave and master. 
Nevertheless the threads should be stopped if the state of the Slave changes. 

![tempsnip](https://user-images.githubusercontent.com/51082544/60980509-e6f5b500-a334-11e9-87cd-58ac3b932700.png)
The info messages is generated in `doSteps()` by myself.

**Comment by dev-gb** [comment]
any updates about this?

Can be tested with Example Master and Slave. 
OpMode=SRT and set the clock of the master 1 minute behind the slave clock.

**Comment by clemensschiffer** [comment]
fixed by #49
