### ISSUE TITLE
String and Binary Variables

### ISSUE THREAD

**Issue by dev-gb** [modelica/DCPLib#22]
Lenght calculation  when receiving string DAT_input_output PDUs seems to be wrong.

Log from DcpSlave.
![Unbenannt](https://user-images.githubusercontent.com/51082544/63675895-1c256c00-c7ea-11e9-9e84-c8e1e4d80960.PNG)

https://github.com/modelica/DCPLib/blob/dad399cbb78a1ff3ba755acf1f52c9e18f8529c3/include/core/dcp/logic/AbstractDcpManagerSlave.hpp#L1557-L1563
correct length should be calculated with the payload length

**Comment by dev-gb** [comment]
my fault. sent a std::string instead of a DcpString. 
Could some of you include the string and binary example as a wiki page.
It took a while to find it in the closed issues
https://github.com/modelica/DCPLib/issues/3#issuecomment-484683727

**Comment by martinkrammer** [comment]
A Wiki entry was added. Closed.
