### ISSUE TITLE
String Output Variables (also Binary)

### ISSUE THREAD

**Issue by clemensschiffer** [modelica/DCPLib#3]
Hello!
How can this code be used to create Output Variables of type String?
I assume by using the make_Output_String_ptr method for the slaveDescription etc.

But Creating DcpManagerSlave with a slaveDescription containing such a Variable crashes the program with  Segmentation fault (core dumped) for me. 
See https://github.com/clemensschiffer/DCPLib/tree/SendString_test for a minimal example.

Many thanks

**Comment by clemensschiffer** [comment]
aha! Its because var.Input is referenced without checking if its is nullptr regardless of In or Output. 
Thats why its no problem with inputs
In AbstractDcpManagerSlave. hpp line 858
if (var.Input.get()->String.get()->maxSize != nullptr)

**Comment by ChKater** [comment]
Yes you are right. I will fix this today in the evening.

**Comment by clemensschiffer** [comment]
Great! Thanks! No hurry :)
I have moved the setting of maxSize lower so now more crash.
In a simple send/receive string example i now get :
A PDU with invalid length received. 9 (received) != 5 (expected).
See my branch https://github.com/clemensschiffer/DCPLib/tree/SendString_test.
Am I doing this wrong?

**Comment by ChKater** [comment]
There was two more bugs. They are corrected now. This was also related to the invalid length. 

But there is also something wrong in your code. Because a dip string has its length as uint32 prefix at front of the binary value of the string. This is incompatible with std::string. Therefore you have to use the class DcpString. 

Here is a snippet who you need to do this. 

```
void configure() {
        simulationTime = 0;
        currentStep = 0;

        a = manager->getInput<char*>(a_vr);
        aStr = new DcpString(a);
        y = manager->getOutput<char*>(y_vr);
        yStr = new DcpString(y);
}

void doStep(uint64_t steps) {
        float64_t timeDiff =
                ((double) numerator) / ((double) denominator) * ((double) steps);

	std::cout << "Value of output " << yStr->getString() << std::endl;
	std::cout << "Value of input "   << aStr->getString() << std::endl;

        if(simulationTime > 3.0){
                      std::string tmp = "foo";
                      yStr->setString(tmp);
        }
		
        simulationTime += timeDiff;
        currentStep += steps;
}

char* a;
DcpString* aStr;
const uint32_t a_vr = 2;

char* y;
DcpString* yStr;
const uint32_t y_vr = 1;
```

I will add a section how tu use string and binary to the wiki next week.

**Comment by clemensschiffer** [comment]
Yes! This works. Thank you very much!
