### ISSUE TITLE
Consults several questions about network communication protocol of dcp.

### ISSUE THREAD

**Issue by lsclone** [modelica/DCPLib#33]
Hi, all!
I download dcplib and run example successfully.
I find that there are 5 types of transport protocol in enum class "DcpTransportProtocol", they are tcp, udp, can, bluetooth and usb. But, in driver module , i only find tcp, udp and bluetooth.
Actually, I would like to run a co-simulation using dcp to achieve a goal that the time loss for each co-simulation step is controlled within 2 milliseconds. How about CAN , USB and bluetooth transport protocol？ If you have any example for these three transport protocols, could you send it to my email  lsclone@outlook.com  ?
Best regards,
Yours.

**Comment by martinkrammer** [comment]
The DCP specification includes 5 protocols, which were tested in scope of the ACOSAR project.
The DCPLib open source software implements UDP and TCP only, at this point in time.
