### ISSUE TITLE
cross-compiling Mingw Linux->Win

### ISSUE THREAD

**Issue by clemensschiffer** [modelica/DCPLib#5]
Hello,

I tried to cross-compile  on Ubunut 18.04 for Windows and had the following issues:

I successfully  build the dependencies(Xerces, libzip) with the same Toolchain file as DCP.

Running `./build_mingw.sh` gives: ASIO headers could not be found.
So I forced `set(ASIO_ROOT /abs_path_to_asio/)` in FindASIO.cmake
This leads to the error:
```

/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/include/c++/cstdlib:75:15: fatal error: stdlib.h: No such file or directory 
#include_next <stdlib.h>

```
Similar to  https://github.com/Martchus/tageditor/issues/22 i tried replacing -isystem with -I which lead to lots of errors of the type

`'thread is not a member of std'`

Is it not possible to compile code using std:threads, mutex etc with mingw out of the box? 
I also tried https://github.com/meganz/mingw-std-threads  but no luck :(
Has someone had similar issues?

It would be nice to be able to produce windows executable with this code.

Kind regard 
Clemens

**Comment by ChKater** [comment]
You need to choose mingw with posix threads instead of win32. 
If you have installed the packages mingw-w64 gcc-mingw-w64-x86-64 try: 
update-alternatives --config x86_64-w64-mingw32-gcc
update-alternatives --config x86_64-w64-mingw32-g++
and choose posix.

**Comment by ChKater** [comment]
For Asio: 
gcc and mingw-gcc use different include directories. You need to install Asio for mingw additionally.

**Comment by clemensschiffer** [comment]
Thank you I will try that.

**Comment by clemensschiffer** [comment]
Yes! This works for me!

For reference:
I installed ASIO like you said but still had to set(ASIO_ROOT /usr/x86_64-w64-mingw32) 
also replace -isystem by -I between configuring and building.
With the same setting the examples compiled and run on windows as expected.

Thank you very much!
