### ISSUE TITLE
two or more slaves

### ISSUE THREAD

**Issue by femust** [modelica/DCPLib#57]
Hey, can you provide an example how to use two slaves?

**Comment by clemensschiffer** [comment]
Hello,

the implementation of the slaves the same, if they are in a scenario with other slaves or not, they just have to have different ip/port and uuid.

For the master:
Sending to different slaves can be implemented like so (see [here](https://github.com/modelica/DCPLib/wiki/3.4-Master-Tools#sending-pdus)):

```
 driver.setSlaveNetworkInformation(1, netInfo1);
 driver.setSlaveNetworkInformation(2, netInfo2);

 manager->CFG_scope(1, 1, DcpScope::CONFIGURED_INITIALIZING_INITIALIZED_RUNNING);
 manager->CFG_scope(2, 1, DcpScope::CONFIGURED_INITIALIZING_INITIALIZED_RUNNING);
```

Then one CFG_scope will be sent to netInfo1 and one to netInfo2. The driver keeps a mapping slaveId -> netInfo and will send to the right address based on the slaveId.

Since the master implementation is client based, reacting to the state changes of connected slaves, we need to synchronize the configuration, e.g. only send stc_run when both slaves have reached state configured etc...

Maybe I can upload an example, I am sure other might be interested as well.

Kind regards,
Clemens

**Comment by femust** [comment]
Correct me if I'm wrong, but this: 
```
DcpScope::CONFIGURED_INITIALIZING_INITIALIZED_RUNNING
```
does not exist in the current implementation? 
```
enum class DcpScope : uint8_t {
    /**
     * Configuration PDUs for data ids with scope Initialization_Run_NonRealTime are valid in the superstates
     * Initialization, Run & NonRealTime.
     */
    Initialization_Run_NonRealTime = 0x00,
    /**
     * Configuration PDUs for data ids with scope Initialization_Run_NonRealTime are valid in the superstates
     * Initialization.
     */
    Initialization = 0x01,
    /**
     * Configuration PDUs for data ids with scope Initialization_Run_NonRealTime are valid in the superstates
     * Run & NonRealTime.
     */
    Run_NonRealTime = 0x02,
};
```

**Comment by clemensschiffer** [comment]
Yes,
I just copied it from the linked wiki, what it tires to say is use:
`manager->CFG_scope(slaveId, dataId, scope); `
with scope being one of Initialization_Run_NonRealTime, Initialization, Run_NonRealTime. 
I guess we should formulate that more clearly.

**Comment by clemensschiffer** [comment]
Hi,
the dataId can be chosen by the master and represents a data connection - corresponding inputs and outputs must share a dataId.
It can be used to group outputs together.
Example: two outputs of slave A to inputs of slave B, if both outputs have the same dataId they will be put into one data pdu. If the dataId is different two data pdus will be sent.
See section 3.4.5 of the standard https://dcp-standard.org/assets/specification/DCP_Specification_v1.0.pdf.

**Comment by clemensschiffer** [comment]
Hi,

I have added an example scenario that demonstrates the use of the slaves. 
Its the typical Co-Simulation example of a mass-damper-spring coupling.

For the master implementation:
Note how the network info of one slave is sent to the other also how dataId of in/ouputs are configured.
Additionally the master waits at certain points to make sure the slave states are in the same state.
Of course for a implementation with error handling etc you have to make sure the calls of the master are non blocking so that it react to different states it configures.

Kind regards 
Clemens

**Comment by femust** [comment]
Hey, thanks for your all information & code examples, I really, really appreciate it!

**Comment by femust** [comment]
If i want to run dcplib in a distributed manner on two pcs (LAN connection), is there something else that I need to do despite configuration description.xml?
one PC IP: 192.160.10.100 (master)
one PC IP: 192.160.10.100 (slave 1)
second PC IP: 192.160.10.105 (slave 2)

```
<TransportProtocols>
        <UDP_IPv4>
            <Control host="192.160.10.105" port="8085"/>
            <DAT_input_output host="127.0.0.1">
                <AvailablePortRange from="2048" to="65535"/>
            </DAT_input_output>
            <DAT_parameter host="127.0.0.1">
                <AvailablePortRange from="2048" to="65535"/>
            </DAT_parameter>
        </UDP_IPv4>
    </TransportProtocols>
```

I am getting an error that from the slave1 (from the PC where is the master)
```
terminate called after throwing an instance of 'std::system_error'
  what():  bind: Cannot assign requested address
Aborted
```
and PC2 seems to not be touched by anything....
should I do something additionally?

**Comment by femust** [comment]
I think that in the example that you were  in order to make it work in the distributed system [https://github.com/modelica/DCPLib/blob/master/example/spring_damper_master/src/MasterModel.h#L105](here) should be 

```
   manager->CFG_source_network_information_UDP(1, 2, asio::ip::address_v4::from_string(
                *slaveDescription1->TransportProtocols.UDP_IPv4->Control->host).to_ulong(), port1);
```
and
```
  manager->CFG_source_network_information_UDP(2, 1, asio::ip::address_v4::from_string(
                *slaveDescription2->TransportProtocols.UDP_IPv4->Control->host).to_ulong(), port2);
```

**Comment by clemensschiffer** [comment]
Yes, you are correct!
That was a copy-paste error, it was only tested on a single machine, thank you for the correction.

If this clears up how to implement for more than one slave, I'll close this issue.

Kind regards

**Comment by femust** [comment]
Yeap, thanks a lot @clemensschiffer !

**Comment by clemensschiffer** [comment]
You _can_ send the same variable twice as in 

```
      manager->CFG_output(1, 1, 0,
                          slaveDescription1->Variables.at(1).valueReference);
      manager->CFG_output(1, 1, 1,
                          slaveDescription1->Variables.at(1).valueReference);
```
that's allowed, but probably not what you want. This would be e.g. if a = 0.6 then output payload =[0.6, 0.6].
You _can not_ assign a variable twice as in 
```
   manager->CFG_input(2, 1, 0,
                         slaveDescription2->Variables.at(0).valueReference,
                         DcpDataType::float64);

      manager->CFG_input(2, 1, 1,
                         slaveDescription2->Variables.at(0).valueReference,
                         DcpDataType::float64);
```
e.g. if input payload = [0.6, 0.7] then what should the value of the scalar input be? Thus this is not allowed.

If you just want:
slave1 -> slave2 (dataId =1)
slave1 <- slave2 (dataId =2)

remembering the syntax
`CFG_output( SlaveId,  dataId, pos,  sourceVr)`
use:
```
            // slave1
            manager->CFG_output(1, 1, 0, slaveDescription1->Variables.at(0).valueReference);
            manager->CFG_input(1, 2, 0, slaveDescription1->Variables.at(1).valueReference, DcpDataType::float64);

            // slave2
            manager->CFG_output(2, 2, 0, slaveDescription2->Variables.at(0).valueReference);
            manager->CFG_input(2, 1, 0, slaveDescription2->Variables.at(1).valueReference, DcpDataType::float64);
```
make sure that for both slaves the first variable in its description is the output and second is the input or hardcore the value references.

**Comment by femust** [comment]
Hmm so I had the following structure 
        
```
// slave1
manager->CFG_output(1, 1, 0, slaveDescription1->Variables.at(0).valueReference);
manager->CFG_input(1, 2, 0, slaveDescription1->Variables.at(1).valueReference, DcpDataType::float64);

// slave2
manager->CFG_output(2, 2, 0, slaveDescription2->Variables.at(0).valueReference);
manager->CFG_input(2, 1, 0, slaveDescription2->Variables.at(1).valueReference, DcpDataType::float64);
```
but nothing worked (it stucks during configuration phase) and it brought frankly speaking the question.

In terms of description files:
![image](https://user-images.githubusercontent.com/26916586/149119235-baee62c6-5522-497c-bd42-8e22979263e0.png)

it is also as you recommended, but still doesn't work for some weird reasons. If you have any thoughts let me know.

**Comment by femust** [comment]
Hmm, I think I figured, this 
```
 numOfCmd[2] = 8;
```
not sure why, it is somehow related to STC_prepare and
```
manager->setAckReceivedListener<SYNC>(
        std::bind(&MainMasterSimpleModel::receiveAck, this,
                  std::placeholders::_1, std::placeholders::_2));
```

**Comment by clemensschiffer** [comment]
Yes, you need to specify how many config-pdus each slave should acknowledge - which is 9 in the sdm example but maybe 8 in yours if you send one less pdu - only then will the master trigger transition to the next state. 
This is checked here:
```
        receivedAcks[sender]++;
        if (receivedAcks[sender] == numOfCmd[sender]) {
            manager->STC_prepare(sender, DcpState::CONFIGURATION);
        }
```
Of course this is just an example implementation, you could also check which messages were acknowledged react accordingly etc. etc.

**Comment by femust** [comment]
ok got you, hope it's a final question:
sometimes (with different configuration and more slaves) I get the error in log stream
```
2022-01-13 10:42:40 	 DEBUG 		 Pdu was received with content=type_id=RSP_nack sender=1 resp_seq_id=3 exp_seq_id=4 error_code=INVALID_VALUE_REFERENCE

```
to what does it refer to? Should input and output have the same value_references?

**Comment by clemensschiffer** [comment]
Hello,
 INVALID_VALUE_REFERENCE means:

> Indicates that the value reference in
> CFG_input, CFG_output, CFG_parameter, or
> CFG_tunable_parameter is not available
> within that DCP slave.
see p 56 of the reference document.

So the slave receives a VR that it does not have, something is wrong in the configuration of the scenario (the master sends something wrong, look through the cfg_input/output 4th parameter and compare with descriptions).

Generally:  VR of connected input/output may differ, the VR only has meaning in the context of a single slave not the whole scenario.

**Comment by clemensschiffer** [comment]
Seems to be resolved. No problem with DCPLib itself came up, but how to use it(maybewe should document more or make a tutorial)
