### ISSUE TITLE
Response PDU family: field positions

### ISSUE THREAD

**Issue by martinkrammer** [modelica/DCPLib#7]
This is fatal, as it encodes and decodes that way, for the entire family, and can only be detected by using another implementation:

RSP_ack correct offset : see DCP specification v1.0 p49:
1 resp_seq_id
3 sender

_Originally posted by @clemensschiffer in https://github.com/modelica/DCPLib/pull/6#issuecomment-491729065_

**Comment by ChKater** [comment]
Resolved in commit 6ae0b5235c5140a3a2ddb18aa2b8c454d91c6cdb
